# Generated by Django 4.2.9 on 2024-06-20 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalUserCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Emergency_id01", models.CharField(max_length=10, unique=True)),
                ("Emergency_id02", models.CharField(max_length=10, unique=True)),
                ("phone", models.CharField(max_length=13)),
                ("phone_alt", models.CharField(default=None, max_length=13, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                ("birth", models.DateField()),
                ("country", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("pinCode", models.CharField(max_length=6)),
                (
                    "Avatar",
                    models.ImageField(
                        default="Uploads_from_User/profile/avatar/person-circle.svg",
                        upload_to="profile/avatar",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UserCredentials",
                "verbose_name_plural": "AdditionalUserCredentials",
            },
        ),
    ]
