# Generated by Django 4.2.9 on 2024-06-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ContactUser", models.CharField(max_length=100)),
                ("ContactPhone", models.CharField(max_length=20)),
                ("ContactEmail", models.CharField(max_length=150)),
                ("ContactMessage", models.TextField()),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contact",
            },
        ),
    ]
