# Generated by Django 4.2.9 on 2024-06-20 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllProducts",
            fields=[
                ("products_id", models.CharField(max_length=10, unique=True)),
                (
                    "product_sno",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("product_slug", models.SlugField(max_length=255)),
                ("product_image", models.ImageField(upload_to="Sell/")),
                ("product_name", models.CharField(max_length=50)),
                (
                    "product_manufacturer",
                    models.CharField(default="Unknown", max_length=50),
                ),
                ("product_price", models.CharField(default="0.00", max_length=8)),
                (
                    "product_dateAdded",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "product_TimeAdded",
                    models.TimeField(default=django.utils.timezone.now),
                ),
                (
                    "product_desc_sm",
                    models.CharField(
                        default="No Discription from Seller", max_length=300, null=True
                    ),
                ),
                (
                    "product_desc_lg",
                    models.TextField(default="No Discription from Seller", null=True),
                ),
                ("product_seller", models.CharField(max_length=20)),
                ("product_rating", models.IntegerField(default="0", null=True)),
                ("product_origin", models.CharField(max_length=10)),
                ("product_totalOrders", models.IntegerField(default="0", null=True)),
            ],
            options={
                "verbose_name": "AllProduct",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
            ],
            options={
                "verbose_name": "AllCategory",
                "verbose_name_plural": "Category",
            },
        ),
        migrations.CreateModel(
            name="Flavour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flavour_name", models.CharField(max_length=255)),
                ("flavour_slug", models.SlugField(max_length=255)),
                (
                    "flavour_filter_color",
                    models.CharField(default="none", max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "AllFlavours",
                "verbose_name_plural": "Flavours",
            },
        ),
        migrations.CreateModel(
            name="ProductComment",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("Productcomment", models.TextField()),
                (
                    "Productcomment_date_stamp",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "Productcomment_time_stamp",
                    models.TimeField(default=django.utils.timezone.now),
                ),
                (
                    "Productcomment_datetime_stamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("Likes", models.IntegerField(default=0)),
                ("disLike", models.IntegerField(default=0)),
                (
                    "Productpost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.allproducts",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "sno",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("liked", models.BooleanField(null=True)),
                (
                    "icon",
                    models.CharField(
                        default='<i class="bi bi-hand-thumbs-up"></i>', max_length=200
                    ),
                ),
                (
                    "commentIs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcomment",
                    ),
                ),
                (
                    "useris",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Like Record",
                "verbose_name_plural": "Like Record",
            },
        ),
        migrations.CreateModel(
            name="CommentDislike",
            fields=[
                (
                    "sno",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("disliked", models.BooleanField(null=True)),
                (
                    "icon",
                    models.CharField(
                        default='<i class="bi bi-hand-thumbs-down"></i>', max_length=200
                    ),
                ),
                (
                    "commentIs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcomment",
                    ),
                ),
                (
                    "useris",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dislike Record",
                "verbose_name_plural": "Dislike Record",
            },
        ),
        migrations.AddField(
            model_name="allproducts",
            name="product_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.category"
            ),
        ),
        migrations.AddField(
            model_name="allproducts",
            name="product_flavour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.flavour"
            ),
        ),
    ]
